// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrpblhffwdbhbnpcvlsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ycGJsaGZmd2RiaGJucGN2bHNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NDUyMTYsImV4cCI6MjA2NjMyMTIxNn0.Z8CJdoTTUHyMfOOQMLDsVOb94EYFF1sLzYqnyhiTEi0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);